baseURL = 'https://gdg-venezia.github.io/devfest-triveneto/'
languageCode = 'it-IT'
paginate = 6
theme= "coHub"
title = 'DevFest Triveneto'

[Menu]
  # Main Menu
#  [[menu.Main]]
#  name = "Speakers"
#  url= "/speakers/"
#  weight = 1
#  [[menu.Main]]
#  name = "Agenda Venezia"
#  url= "/agenda-venezia/"
#  weight = 2
#  [[menu.Main]]
#  name = "Agenda Trento"
#  url= "/agenda-trento/"
#  weight = 3
  [[menu.Main]]
  name = "Tickets"
  url= "#ticket"
  weight = 4
  [[menu.Main]]
  name = "Partners"
  url= "#partner"
  weight = 5
  [[menu.Main]]
  name = "Location"
  url= "#location"
  weight = 6
  [[menu.Main]]
#  name = "News"
#  url= "/blog"
#  weight = 7

[params]
  copyright = "© {year} <a href=\"https://marcogomiero.com/\" target=\"_blank\">Marco Gomiero </a>"
  googleAnalytics = ""
  logo = "images/logo.svg"
  footerlogo = "images/logo.svg"
  footerDescription = "Organized by Google Developer Group <a href=\"https://gdg.community.dev/gdg-venezia/\" target=\"BLANK\">Venezia</a>, <a href=\"https://gdg.community.dev/gdg-padova/\" target=\"BLANK\">Padova</a>, <a href=\"https://gdg.community.dev/gdg-verona/\" target=\"BLANK\">Verona</a> e <a href=\"https://gdg.community.dev/gdg-trento/\" target=\"BLANK\">Trento</a>."

  [params.location]
  title = "Location"

  [params.location.venezia]
  address = "Campus Scientifico Università Ca' Foscari"
  desc = "Via Torino, 155 Mestre, Venezia VE, 30170"
  mapsLink = "https://www.google.com/maps/dir//Via%20Torino%2C%20155%20Mestre%2C%20Venezia%20VE"

  [params.location.trento]
  address = "Contamination Lab (CLab) Trento"
  desc = "Via Tommaso Gar, 16 Trento, 38122"
  mapsLink = "https://www.google.com/maps/dir//Via%20Tommaso%20Gar%2C%2016%20Trento"


